notes_memorization/notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
    path('', views.index, name='all_notes'),
    path('add_note/', views.add_note),
    path('<int:note_id>/', views.detail, name='detail'),
    path('review/', views.review, name='review'),
    path('download/', views.download),
]

notes_memorization/notes_memorization/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
]

notes_memorization/notes/models.py
from django.db import models


# Create your models here.
class Label(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Project(models.Model):  # like category
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Note(models.Model):
    text = models.TextField()
    labels = models.ManyToManyField(Label)
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    date_added = models.DateTimeField()
    reviews_counter = models.IntegerField(default=0)
    link_url = models.URLField(default='')
    link_file = models.FileField(default=None, null=True)

    def __str__(self):
        return '{} — {}'.format(self.text[:100], self.project)

notes_memorization/notes/views.py
from random import randint
import csv
from lxml import etree

from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from django.http.response import HttpResponseRedirect

from .models import Label, Note, Project
from django.views.decorators.http import require_http_methods
from django.utils import timezone


# Create your views here.
def index(request):
    notes = Note.objects.all()
    projects = Project.objects.all()
    return render(request, 'notes/index.html', context={'notes': notes, 'projects': projects})


@require_http_methods(["POST"])
def add_note(request):
    try:
        note = Note(text=request.POST['new_note'],
                    project=Project.objects.get(pk=request.POST['project_id']),
                    date_added=timezone.now())
        note.save()
        text = 'Added a new note: %s (#%s)' % (note.text, note.id)
        print(text, note.project)
        return HttpResponseRedirect('/notes')
    except:
        return HttpResponse('Error', status=404)


def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    return render(request, 'notes/detail.html', context={'note': note})


@require_http_methods(["GET"])
def review(request):
    id_list = [n.id for n in Note.objects.all()]
    cur_id = request.GET.get('cur_id')
    if cur_id:  # get next note
        if id_list.index(int(cur_id)) == len(id_list) - 1:
            num = id_list[0]  # if the previous note was the last in list, get the first one
        else:
            num = id_list[id_list.index(int(cur_id)) + 1]
        obj = Note.objects.get(pk=num)
        obj.reviews_counter += 1
        obj.save()
        return JsonResponse({'note': str(obj), 'note_id': obj.id})
    else:  # get random note
        num = id_list[randint(0, len(id_list) - 1)]
        obj = Note.objects.get(pk=num)
        obj.reviews_counter += 1
        obj.save()
        return render(request, 'notes/review.html', context={'note': obj})


def download(request):
    try:
        notes = Note.objects.all()
        if request.GET.get('type') == 'csv':
            with open('notes.csv', 'w') as f:
                note_writer = csv.writer(f)
                note_writer.writerow(['ID', 'Text', 'Project', 'Date added', '# of reviews', 'Url', 'File'])
                for note in notes:
                    note_writer.writerow([note.id, note.text, note.project, note.date_added,
                                          note.reviews_counter, note.link_url, note.link_file])

        elif request.GET.get('type') == 'xml':
            root = etree.Element('notes')

            for note in notes:
                n = etree.SubElement(root, 'note')

                for attr in ('id', 'text', 'project', 'date_added', 'reviews_counter', 'link_url', 'link_file'):
                    etree.SubElement(n, attr).text = str(note.__getattribute__(attr))

            etree.ElementTree(root).write('notes.xml', pretty_print=True, xml_declaration=True, encoding='UTF-8')
    except Exception as e:
        return JsonResponse({'result': e})
    else:
        return JsonResponse({'result': True})

notes_memorization/notes/templates/notes/detail.html
{% extends 'base.html' %}

{% block title %}
  Note #{{ note.id }}
{% endblock %}

{% block content %}
  <div class="container" style="width: 65%">
    <div class="row">
      <div class="col-sm">
        <h3>Note #{{ note.id }}</h3>
        <table class="table">
          <tr>
            <th>Text</th>
            <th>Project</th>
            <th>Labels</th>
            <th>Attachments</th>
            <th>Reviews number</th>
          </tr>
          <tr>
            <td>{{ note.text }}</td>
            <td>{{ note.project }}</td>
            <td></td>
            <td>{{ note.reviews_number }}</td>
            <td>{{ note.link_file }}</td>
            <td>{{ note.reviews_counter }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

notes_memorization/notes/templates/notes/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Notes
{% endblock %}

{% block content %}
  <div class="container" style="width: 65%">
    <div class="row mt-3">
      <div class="col-sm">
        <button class="btn btn-primary" onclick="location.href='/notes/review'">Review</button>
        <button class="btn btn-dark" onclick="exp_data('csv')">Export in csv</button>
        <button class="btn btn-dark" onclick="exp_data('xml')">Export in xml</button>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm">
        <h2>Notes manager</h2>

        <form action="add_note/" method="POST" id="newNote" enctype="multipart/form-data">
          {% csrf_token %}
          <label for="note_text">Enter your note</label>
          <input type="text" name="new_note" placeholder="Some text" id="note_text" autocomplete="off"/>
          <br>
          <br>
          <label for="project_select">Select project</label>
          <select name="project_id" id="project_select">
            {% for proj in projects %}
              <option value="{{ proj.id }}">{{ proj }}</option>
            {% endfor %}
          </select>
          <br>
          <br>
          <input type="file" />
          <br>
          <br>
          <button class="btn btn-outline-dark" type="submit">Add a note</button>
        </form>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm">
        {% if notes %}
          <h4>Notes:</h4>
          <table class="table table-light table-hover">
            <tr>
              <th>#</th>
              <th>Text</th>
              <th>Project</th>
              <th>Labels</th>
            </tr>
            {% for note in notes %}
              <tr>
                <td><a href="{% url 'notes:detail' note.id %}">{{ note.id }}</a></td>
                <td>{{ note.text }}</td>
                <td>{{ note.project }}</td>
                <td></td>
              </tr>
            {% endfor %}
          </table>
        {% else %}
          <p>No notes are available</p>
        {% endif %}
      </div>
    </div>
  </div>

  <script>
    function exp_data(type) {
      $.ajax({
        type: "GET",
        url: "download/",
        data: {'type': type},
        success: function(data) {

        }
      });
    }
  </script>
{% endblock %}

notes_memorization/notes/templates/notes/review.html
{% extends 'base.html' %}
{% block title %}
  Review
{% endblock %}

{% block content %}
  <div class="container" style="width: 65%">
    <div class="row">
      <div class="col-sm">
        <p id="note">{{ note }}</p>
        <input id="noteId" value="{{ note.id }}" hidden>
        <button class="btn btn-success" onclick="getNextNote()">Next note</button>
        <button class="btn btn-success" onclick="getRandomNote()">Random note</button>
        <button class="btn btn-danger" onclick="location.href='/notes'">Finish review</button>

      </div>
    </div>
  </div>


  <script>
    function getNextNote() {
      $.ajax({
        type: "GET",
        url: "#",
        data: {'cur_id': $('#noteId').val()},
        success: function (data) {
          $('#note').text(data['note']);
          $('#noteId').val(data['note_id']);
        }
      });
    }

    function getRandomNote() {
      $.ajax({
        type: "GET",
        url: "#",
        success: function (data) {
          location.reload();
        }
      });
    }
  </script>
{% endblock %}

notes_memorization/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>


  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
</head>

<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Home</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        {% if user.is_staff %}
          <li class="nav-item"><a class="nav-link" href="/admin/">Admin panel</a></li>
        {% endif %}
        <li class="nav-item"><a class="nav-link" href="/notes/">Notes</a></li>
      </ul>
    </div>

    {% if user.is_authenticated %}
      <span class="navbar-text">Hi, <b>{{ user.username }}</b>!</span>
      <ul class="navbar-nav">

      </ul>
    {% else %}
      <ul class="navbar-nav">

      </ul>
    {% endif %}
  </nav>

  {% block content %}
  {% endblock %}
</body>
</html>